### ISSUE TITLE
Please support at least ES6 syntax to be downward compatible

### ISSUE THREAD

**Issue by nykevinwong** [jo-te/node-freemarker#3]
Hi node-freemarker Developer,
unfortunately, this library is using a ES7 feature and does NOT support ES6 syntax.
This means that developers will either need to upgrade their project to ES7 compatible or pick another library.

...\src\themes\node_modules\node-freemarker\src\engine.js:29
  constructor(templateRoot, globals = {}, options = {}) {
                                    ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Module._extensions..js (module.js:416:10)
    at Object.require.extensions.(anonymous function) [as .js] (...\src\themes\node_modules\babel-register\lib\node.js:152:7)

**Comment by nykevinwong** [comment]
In addition, I did not see any unit testings created for this project. Unit testing can be created to prove target use cases of this project work and it also ensures other developers won't break the existing feature of this project code when trying to fix/add a new feature.

**Comment by jo-te** [comment]
Downgraded code to ES6 and added some tests. Until now there is only testing for the `renderFileAsync` method, since `renderStringAsync` and `renderFileAsync` are using the same method under the hood. Will add further tests soon. :)
